### ISSUE TITLE
Fenix's HeroWeaponDamage is not available in JSON output

### ISSUE THREAD

**Issue by pastelmind** [joeistas/heroes-parser#1]
I'm running heroes-parser with `--profile detailed`. The output JSON for Fenix (`Fenix.json`) is missing the base weapon damage value (86). Specifically, the following element in `FenixData.xml` is removed:

```xml
  <CEffectDamage id="FenixHeroWeaponDamage" parent="StormWeapon">
    <Amount value="86" />
    <MultiplicativeModifierArray index="0" Validator="FenixHasMobileOffenseDamageBuffAndTargetIsHero" Modifier="0.3" Crit="1" />
  </CEffectDamage>
```

Can the `detailed` profile please be updated to include this value?

**Comment by joeistas** [comment]
Thanks for the bug report @pastelmind, this should be fixed in v1.0.9.
