### ISSUE TITLE
JSON saved to wrong path since HotS 36.0

### ISSUE THREAD

**Issue by pastelmind** [joeistas/heroes-parser#3]
Running `heroes-parser parse <game dir>` results in the program generating a *single* JSON file at `./67143/basic/heroes/[object Object].json`. The [contents of this JSON file](https://gist.github.com/pastelmind/088aa0c8ef8c3b9f2c758ae2e430e281) is garbled.

Running with `--profile detailed` also results in a single garbled JSON file, at `./67143/detailed/heroes/[object Object].json`

I've tried the following variations of the command, but the problem persists. (powershell btw)

```powershell
heroes-parser parse 'C:\Program Files (x86)\Heroes of the Storm'
heroes-parser parse 'C:\Program Files (x86)\Heroes of the Storm' --profile detailed
heroes-parser parse 'C:\Program Files (x86)\Heroes of the Storm\HeroesData\' --profile detailed
```

I'm running Heroes of the Storm 2.36.0.67143 (Korean) / heroes-parser v1.0.10 . I've tried downgrading `heroes-parser` to 1.0.9, but the problem still persists--I suspect that the issue is caused by a change in the game data files.

**Comment by joeistas** [comment]
Fixed in 1.0.11
